#Import Libraries

In [ ]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

# Gathering Data for Each Year

## 2022

### Schools List

In [ ]:
# Initialize empty lists to store school data from the website
npsn = []
sekolah = []
nilai_total = []
provinsi = []
kota = []
jenis = []

# Base URL for scraping data from the top 1000 schools website
base_url = 'https://top-1000-sekolah.ltmpt.ac.id/?page='

# Loop through each pages of the website
for page in range(1,11) :
  url = base_url + str(page)
  response = requests.get(url)
  soup = BeautifulSoup(response.content, 'html5lib') # Parse the page content using BeautifulSoup

  awal_page = 1 + 100*(page-1) # Start of the current page (e.g., 1 for page 1, 101 for page 2)
  akhir_page = awal_page+ 99 # End of the current page (e.g., 100 for page 1, 200 for page 2)

  # Loop through each row (representing a school) on the current page
  for i in range(awal_page,akhir_page+1) :
    table_row = soup.find('tr',{'data-key' : i})
    td_npsn = table_row.find_all('td')[2]
    td_sekolah = table_row.find_all('td')[3]
    td_nilai_total = table_row.find_all('td')[4]
    td_provinsi = table_row.find_all('td')[5]
    td_kota = table_row.find_all('td')[6]
    td_jenis = table_row.find_all('td')[7]
    npsn.append(td_npsn.text)
    sekolah.append(td_sekolah.text)
    nilai_total.append(td_nilai_total.text)
    provinsi.append(td_provinsi.text)
    kota.append(td_kota.text)
    jenis.append(td_jenis.text)

### Sub-test

In [ ]:
# Initialize empty lists to store subtest scores for each school
pk = []
pbm = []
pu = []
ppu = []

# Base URL for retrieving detailed subtest scores from the website
base_url_subtes = 'https://top-1000-sekolah.ltmpt.ac.id/site/page2022?id='

# Loop through the first 1000 schools (IDs range from 1 to 1000)
for i in range(1,1001) :
  url = base_url_subtes + str(i)
  r = requests.get(url)
  soup_nilai = BeautifulSoup(r.content, 'html5lib')
  nilai_pk = soup_nilai.find_all('b')[6].text #Nilai PK
  nilai_pbm = soup_nilai.find_all('b')[8].text #Nilai PBM
  nilai_pu = soup_nilai.find_all('b')[10].text #Nilai PU
  nilai_ppu = soup_nilai.find_all('b')[12].text #Nilai PPU
  pk.append(nilai_pk)
  pbm.append(nilai_pbm)
  pu.append(nilai_pu)
  ppu.append(nilai_ppu)

### Create DataFrame

In [ ]:
rank = list(range(1,1001))
tabel_2022 = pd.DataFrame(list(zip(rank, npsn, sekolah, provinsi, kota, jenis, nilai_total, pk, pbm, pu, ppu)), columns = ['Peringkat','NPSN', 'Nama Sekolah', 'Provinsi', 'Kota/Kabupaten', 'Jenis', 'Nilai Total', 'PK', 'PBM', 'PU', 'PPU'])
tabel_2022.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20623314,MAN INSAN CENDEKIA SERPONG More..,Prov. Banten,Kota Tangerang Selatan,MA,"666,494","683,5","680,86","691,36","663,14"
1,2,20532145,SMA KATOLIK ST.LOUIS 1 More..,Prov. Jawa Timur,Kota Surabaya,SMA,"641,482","672,13","648,65","650,48","644,69"
2,3,69978389,SMA PRADITA DIRGANTARA More..,Prov. Jawa Tengah,Kab. Boyolali,SMA,"640,747","583,57","657,62","666,89","697,36"
3,4,69941723,MAN INSAN CENDEKIA PEKALONGAN More..,Prov. Jawa Tengah,Kota Pekalongan,MA,"637,499","658,5","645,66","663,82","629,44"
4,5,20102568,SMAN 8 JAKARTA More..,Prov. D.K.I. Jakarta,Kota Jakarta Selatan,SMA,"635,347","662,4","653,91","658,45","641,47"

# 2021

### Schools List

In [90]:
# Initialize empty lists to store subtest scores for each school
npsn_2021 = []
sekolah_2021 = []
nilai_total_2021 = []
provinsi_2021 = []
kota_2021 = []
jenis_2021 = []

# Base URL for scraping data from the top 1000 schools website
base_url_21 = 'https://top-1000-sekolah.ltmpt.ac.id/site/index2021?page='

# Loop through each page of the website
for page in range(1,11) :
  url = base_url_21 + str(page)
  response = requests.get(url)
  soup = BeautifulSoup(response.content, 'html5lib')
  awal_page = 1 + 100*(page-1)
  akhir_page = awal_page+100
  for i in range(awal_page,akhir_page) :
    table_row = soup.find('tr',{'data-key' : i})
    td_npsn = table_row.find_all('td')[2]
    td_sekolah = table_row.find_all('td')[3]
    td_nilai_total = table_row.find_all('td')[4]
    td_provinsi = table_row.find_all('td')[5]
    td_kota = table_row.find_all('td')[6]
    td_jenis = table_row.find_all('td')[7]
    npsn_2021.append(td_npsn.text)
    sekolah_2021.append(td_sekolah.text)
    nilai_total_2021.append(td_nilai_total.text)
    provinsi_2021.append(td_provinsi.text)
    kota_2021.append(td_kota.text)
    jenis_2021.append(td_jenis.text)

### Sub-test

In [ ]:
# Initialize empty lists to store subtest scores for each school
pk_2021 = []
pbm_2021 = []
pu_2021 = []
ppu_2021 = []

# Base URL for retrieving detailed subtest scores from the website
base_url_subtes_21 = 'https://top-1000-sekolah.ltmpt.ac.id/site/page2021?id='

for i in range(1,1001) :
  url = base_url_subtes_21 + str(i)
  r = requests.get(url)
  soup_nilai = BeautifulSoup(r.content, 'html5lib')
  nilai_pk = soup_nilai.find_all('b')[6].text #Nilai PK
  nilai_pbm = soup_nilai.find_all('b')[8].text #Nilai PBM
  nilai_pu = soup_nilai.find_all('b')[10].text #Nilai PU
  nilai_ppu = soup_nilai.find_all('b')[12].text #Nilai PPU
  pk_2021.append(nilai_pk)
  pbm_2021.append(nilai_pbm)
  pu_2021.append(nilai_pu)
  ppu_2021.append(nilai_ppu)

### Create DataFrame

In [ ]:
rank = list(range(1,1001))
tabel_2021 = pd.DataFrame(list(zip(rank, npsn_2021, sekolah_2021, provinsi_2021, kota_2021, jenis_2021, nilai_total_2021, pk_2021, pbm_2021, pu_2021, ppu_2021)), columns = ['Peringkat','NPSN', 'Nama Sekolah', 'Provinsi', 'Kota/Kabupaten', 'Jenis', 'Nilai Total', 'PK', 'PBM', 'PU', 'PPU'])
tabel_2021.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20623314,MAN INSAN CENDEKIA SERPONG More..,Banten,Kota Tangerang Selatan,MA,"637,807","706,069","657,756","647,529","678,915"
1,2,20109933,SMAN UNGGULAN M.H. THAMRIN More..,DKI Jakarta,Kota Jakarta Timur,SMA,"635,675","735,338","660,578","665,890","671,555"
2,3,20102568,SMAN 8 JAKARTA More..,DKI Jakarta,Kota Jakarta Selatan,SMA,"630,860","709,985","652,013","655,346","665,519"
3,4,10263538,SMAS UNGGUL DEL More..,Sumatera Utara,Kab. Toba Samosir,SMA,"630,177","698,132","635,296","652,113","650,386"
4,5,20219730,SMAS BPK 1 PENABUR BANDUNG More..,Jawa Barat,Kota Bandung,SMA,"618,415","676,796","635,298","631,393","634,322"

##2020

### Schools List

In [ ]:
base_url_20 = 'https://top-1000-sekolah.ltmpt.ac.id/site/index2020?page='

npsn_2020 = []
sekolah_2020 = []
nilai_total_2020 = []
provinsi_2020 = []
kota_2020 = []
jenis_2020 = []

for page in range(1,11) :
  url = base_url_20 + str(page) + '&per-page=100'
  r = requests.get(url)
  soup = BeautifulSoup(r.content, 'html5lib')
  awal_page = 2001 + 100*(page-1)
  akhir_page = awal_page+100
  for i in range(awal_page,akhir_page) :
    table_row = soup.find('tr',{'data-key' : i})
    td_nilai_total = table_row.find_all('td')[2]
    td_npsn = table_row.find_all('td')[3]
    td_sekolah = table_row.find_all('td')[4]
    td_provinsi = table_row.find_all('td')[5]
    td_kota = table_row.find_all('td')[6]
    td_jenis = table_row.find_all('td')[7]
    npsn_2020.append(td_npsn.text)
    sekolah_2020.append(td_sekolah.text)
    nilai_total_2020.append(td_nilai_total.text)
    provinsi_2020.append(td_provinsi.text)
    kota_2020.append(td_kota.text)
    jenis_2020.append(td_jenis.text)

### Sub-test

In [ ]:
base_url_20_subtes = 'https://top-1000-sekolah.ltmpt.ac.id/site/page?id='
pk_2020 = []
pbm_2020 = []
pu_2020 = []
ppu_2020 = []
for i in range(2001,3001) :
  url = base_url_20_subtes + str(i)
  response = requests.get(url)
  soup = BeautifulSoup(response.content, 'html5lib')
  nilai_pk = soup.find_all('b')[0].text #Nilai PK
  nilai_pbm = soup.find_all('b')[4].text
  nilai_pu = soup.find_all('b')[8].text
  nilai_ppu = soup.find_all('b')[12].text
  pk_2020.append(nilai_pk)
  pbm_2020.append(nilai_pbm)
  pu_2020.append(nilai_pu)
  ppu_2020.append(nilai_ppu)

### Create DataFrame

In [ ]:
rank = list(range(1,1001))
tabel_2020 = pd.DataFrame(list(zip(rank, npsn_2020, sekolah_2020, provinsi_2020, kota_2020, jenis_2020, nilai_total_2020, pk_2020, pbm_2020, pu_2020, ppu_2020)), columns = ['Peringkat','NPSN', 'Nama Sekolah', 'Provinsi', 'Kota/Kabupaten', 'Jenis', 'Nilai Total', 'PK', 'PBM', 'PU', 'PPU'])
tabel_2020.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20109933,SMAN UNGGULAN M.H. THAMRIN More..,DKI Jakarta,Kota Jakarta Timur,SMA,"601,683","640,253","589,104","581,979","595,396"
1,2,20623314,MAN INSAN CENDEKIA SERPONG More..,Banten,Kota Tangerang Selatan,MA,"599,654","628,725","598,09","579,959","591,843"
2,3,10263538,SMAS UNGGUL DEL More..,Sumatera Utara,Kab. Toba Samosir,SMA,"598,523","654,285","592,814","575,067","571,927"
3,4,20102568,SMAN 8 JAKARTA More..,DKI Jakarta,Kota Jakarta Selatan,SMA,"594,865","635,235","583,244","570,441","590,54"
4,5,20532248,SMAN 5 SURABAYA More..,Jawa Timur,Kota Surabaya,SMA,"594,605","623,709","588,156","579,398","587,157"

#Data Processing

## 2022

In [ ]:
tabel_2022['Nama Sekolah'] = tabel_2022['Nama Sekolah'].str.slice(0,-7)
tabel_2022['Provinsi'] = tabel_2022['Provinsi'].str.slice(6)
tabel_2022['Nilai Total'] = tabel_2022['Nilai Total'].str.replace(',','.')
tabel_2022['PK'] = tabel_2022['PK'].str.replace(',','.')
tabel_2022['PBM'] = tabel_2022['PBM'].str.replace(',','.')
tabel_2022['PU'] = tabel_2022['PU'].str.replace(',','.')
tabel_2022['PPU'] = tabel_2022['PPU'].str.replace(',','.')
tabel_2022['Nilai Total'] = tabel_2022['Nilai Total'].astype(float)
tabel_2022['PK'] = tabel_2022['PK'].astype(float)
tabel_2022['PBM'] = tabel_2022['PBM'].astype(float)
tabel_2022['PU'] = tabel_2022['PU'].astype(float)
tabel_2022['PPU'] = tabel_2022['PPU'].astype(float)
tabel_2022.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20623314,MAN INSAN CENDEKIA SERPONG,Banten,Kota Tangerang Selatan,MA,666.494,683.50,680.86,691.36,663.14
1,2,20532145,SMA KATOLIK ST.LOUIS 1,Jawa Timur,Kota Surabaya,SMA,641.482,672.13,648.65,650.48,644.69
2,3,69978389,SMA PRADITA DIRGANTARA,Jawa Tengah,Kab. Boyolali,SMA,640.747,583.57,657.62,666.89,697.36
3,4,69941723,MAN INSAN CENDEKIA PEKALONGAN,Jawa Tengah,Kota Pekalongan,MA,637.499,658.50,645.66,663.82,629.44
4,5,20102568,SMAN 8 JAKARTA,D.K.I. Jakarta,Kota Jakarta Selatan,SMA,635.347,662.40,653.91,658.45,641.47

## 2021

In [ ]:
tabel_2021['Nama Sekolah'] = tabel_2021['Nama Sekolah'].str.slice(0,-7)
tabel_2021['Nilai Total'] = tabel_2021['Nilai Total'].str.replace(',','.')
tabel_2021['PK'] = tabel_2021['PK'].str.replace(',','.')
tabel_2021['PBM'] = tabel_2021['PBM'].str.replace(',','.')
tabel_2021['PU'] = tabel_2021['PU'].str.replace(',','.')
tabel_2021['PPU'] = tabel_2021['PPU'].str.replace(',','.')
tabel_2021['Nilai Total'] = tabel_2021['Nilai Total'].astype(float)
tabel_2021['PK'] = tabel_2021['PK'].astype(float)
tabel_2021['PBM'] = tabel_2021['PBM'].astype(float)
tabel_2021['PU'] = tabel_2021['PU'].astype(float)
tabel_2021['PPU'] = tabel_2021['PPU'].astype(float)
tabel_2021.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20623314,MAN INSAN CENDEKIA SERPONG,Banten,Kota Tangerang Selatan,MA,637.807,706.069,657.756,647.529,678.915
1,2,20109933,SMAN UNGGULAN M.H. THAMRIN,DKI Jakarta,Kota Jakarta Timur,SMA,635.675,735.338,660.578,665.890,671.555
2,3,20102568,SMAN 8 JAKARTA,DKI Jakarta,Kota Jakarta Selatan,SMA,630.860,709.985,652.013,655.346,665.519
3,4,10263538,SMAS UNGGUL DEL,Sumatera Utara,Kab. Toba Samosir,SMA,630.177,698.132,635.296,652.113,650.386
4,5,20219730,SMAS BPK 1 PENABUR BANDUNG,Jawa Barat,Kota Bandung,SMA,618.415,676.796,635.298,631.393,634.322

## 2020

In [ ]:
tabel_2020['Nama Sekolah'] = tabel_2020['Nama Sekolah'].str.slice(0,-7)
tabel_2020['Nilai Total'] = tabel_2020['Nilai Total'].str.replace(',','.')
tabel_2020['PK'] = tabel_2020['PK'].str.replace(',','.')
tabel_2020['PBM'] = tabel_2020['PBM'].str.replace(',','.')
tabel_2020['PU'] = tabel_2020['PU'].str.replace(',','.')
tabel_2020['PPU'] = tabel_2020['PPU'].str.replace(',','.')
tabel_2020['Nilai Total'] = tabel_2020['Nilai Total'].astype(float)
tabel_2020['PK'] = tabel_2020['PK'].astype(float)
tabel_2020['PBM'] = tabel_2020['PBM'].astype(float)
tabel_2020['PU'] = tabel_2020['PU'].astype(float)
tabel_2020['PPU'] = tabel_2020['PPU'].astype(float)
tabel_2020.head(5)

,Peringkat,NPSN,Nama Sekolah,Provinsi,Kota/Kabupaten,Jenis,Nilai Total,PK,PBM,PU,PPU
0,1,20109933,SMAN UNGGULAN M.H. THAMRIN,DKI Jakarta,Kota Jakarta Timur,SMA,601.683,640.253,589.104,581.979,595.396
1,2,20623314,MAN INSAN CENDEKIA SERPONG,Banten,Kota Tangerang Selatan,MA,599.654,628.725,598.090,579.959,591.843
2,3,10263538,SMAS UNGGUL DEL,Sumatera Utara,Kab. Toba Samosir,SMA,598.523,654.285,592.814,575.067,571.927
3,4,20102568,SMAN 8 JAKARTA,DKI Jakarta,Kota Jakarta Selatan,SMA,594.865,635.235,583.244,570.441,590.540
4,5,20532248,SMAN 5 SURABAYA,Jawa Timur,Kota Surabaya,SMA,594.605,623.709,588.156,579.398,587.157

#Save Data Frame to CSV

In [ ]:
data_22 = tabel_2022.to_excel('/content/top-1000-utbk-2022.xlsx',index = False)
data_21 = tabel_2021.to_excel('/content/top-1000-utbk-2021.xlsx',index = False)
data_20 = tabel_2020.to_excel('/content/top-1000-utbk-2020.xlsx',index = False)